// <auto-generated />
namespace PesquisaEleitoral_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AdminRemove : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdminRemove));
        
        string IMigrationMetadata.Id
        {
            get { return "201609170024412_AdminRemove"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
